import Head from 'next/head'
import Image from 'next/image'
import { Footer } from '../components/Footer'
import styles from '../styles/Home.module.css'
import { Links } from '../components/Links'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>about page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          About Page <a href = "http://localhost:3000/">Index Page</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/about.js</code>
        </p>

        <Links />

      </main>

      <Footer />

    </div>
  )
}
